# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genetic_algorithm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from populacja import Populacja
from FitnessFunction import FitnessFunction
import matplotlib.pyplot as plt



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(311, 527)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 490, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.selectionMethodCombo = QtWidgets.QComboBox(Dialog)
        self.selectionMethodCombo.setGeometry(QtCore.QRect(10, 330, 291, 22))
        self.selectionMethodCombo.setObjectName("selectionMethodCombo")
        self.selectionMethodCombo.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 310, 111, 16))
        self.label.setObjectName("label")
        self.startRange = QtWidgets.QLineEdit(Dialog)
        self.startRange.setGeometry(QtCore.QRect(10, 10, 291, 22))
        self.startRange.setObjectName("startRange")
        self.endRange = QtWidgets.QLineEdit(Dialog)
        self.endRange.setGeometry(QtCore.QRect(10, 40, 291, 22))
        self.endRange.setObjectName("endRange")
        self.populationAmount = QtWidgets.QLineEdit(Dialog)
        self.populationAmount.setGeometry(QtCore.QRect(10, 70, 291, 22))
        self.populationAmount.setText("100")
        self.populationAmount.setObjectName("populationAmount")
        self.numberOfEpoch = QtWidgets.QLineEdit(Dialog)
        self.numberOfEpoch.setGeometry(QtCore.QRect(10, 130, 291, 22))
        self.numberOfEpoch.setText("40")
        self.numberOfEpoch.setObjectName("numberOfEpoch")
        self.bestAndTourmamentChromosomeAmount = QtWidgets.QLineEdit(Dialog)
        self.bestAndTourmamentChromosomeAmount.setGeometry(QtCore.QRect(10, 160, 291, 22))
        self.bestAndTourmamentChromosomeAmount.setObjectName("bestAndTourmamentChromosomeAmount")
        self.eliteStrategyAmount = QtWidgets.QLineEdit(Dialog)
        self.eliteStrategyAmount.setGeometry(QtCore.QRect(10, 190, 291, 22))
        self.eliteStrategyAmount.setObjectName("eliteStrategyAmount")
        self.crossProbability = QtWidgets.QLineEdit(Dialog)
        self.crossProbability.setGeometry(QtCore.QRect(10, 220, 291, 22))
        self.crossProbability.setObjectName("crossProbability")
        self.mutationProbability = QtWidgets.QLineEdit(Dialog)
        self.mutationProbability.setGeometry(QtCore.QRect(10, 250, 291, 22))
        self.mutationProbability.setObjectName("mutationProbability")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 360, 101, 16))
        self.label_2.setObjectName("label_2")
        self.crossMethodCombo = QtWidgets.QComboBox(Dialog)
        self.crossMethodCombo.setGeometry(QtCore.QRect(10, 380, 291, 22))
        self.crossMethodCombo.setObjectName("crossMethodCombo")
        self.crossMethodCombo.addItem("")
        self.crossMethodCombo.addItem("")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 410, 111, 16))
        self.label_3.setObjectName("label_3")
        self.mutationMethodCombo = QtWidgets.QComboBox(Dialog)
        self.mutationMethodCombo.setGeometry(QtCore.QRect(10, 430, 291, 22))
        self.mutationMethodCombo.setObjectName("mutationMethodCombo")
        self.mutationMethodCombo.addItem("")
        self.mutationMethodCombo.addItem("")
        self.inversionProbability = QtWidgets.QLineEdit(Dialog)
        self.inversionProbability.setGeometry(QtCore.QRect(10, 280, 291, 22))
        self.inversionProbability.setObjectName("inversionProbability")
        self.numberOfBits = QtWidgets.QLineEdit(Dialog)
        self.numberOfBits.setGeometry(QtCore.QRect(10, 100, 291, 22))
        self.numberOfBits.setObjectName("numberOfBits")
        self.maximizationCheckBox = QtWidgets.QCheckBox(Dialog)
        self.maximizationCheckBox.setGeometry(QtCore.QRect(10, 460, 111, 20))
        self.maximizationCheckBox.setObjectName("maximizationCheckBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(lambda: self.runGen(int(self.numberOfEpoch.text()),int(self.populationAmount.text()))) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def generateFiles(self, epoki):
        values = []
        bestValues = []
        means = []
        standardDeviations = []
        f = FitnessFunction()
        for populacja in epoki:
            for osobnik in populacja.population:
                decoded = osobnik.decode(-10, 10, -10, 10)
                #wartości funkcji dla każdego osobnika w danej populacji
                values.append(f.value(decoded[0], decoded[1]))
            else:
                #najlepsza wartość funkcji dla danej populacji
                best = populacja.findBest().decode(-10, 10, -10, 10)
                bestValues.append(f.value(best[0], best[1]))
                #średnia wartość funkcji dla danej populacji
                means.append(sum(values)/len(values))
                nominator = 0
                for value in values:
                    nominator += pow(value - means[-1], 2)
                #odchylenie standardowe dla danej populacji
                standardDeviations.append(pow(nominator/len(values), 0.5))
                values.clear()

        bestValuesFile = open("best_values.txt", "w")
        meansFile = open("means.txt", "w")
        standardDeviationsFile = open("standard_deviations.txt", "w")
        for i in range(len(bestValues)):
            bestValuesFile.write(str(i) + ": " + str(bestValues[i]) + "\n")
            meansFile.write(str(i) + ": " + str(means[i]) + "\n")
            standardDeviationsFile.write(str(i) + ": " + str(standardDeviations[i]) + "\n")

        bestValuesFile.close()
        meansFile.close()
        standardDeviationsFile.close()

        plt.plot(bestValues)
        plt.title("DROP-WAVE FUNCTION - best values per iteration")
        plt.xlabel('Iterations')
        plt.ylabel('Best values')
        plt.savefig("best_values.png")
        plt.clf()
        plt.cla()

        plt.plot(means)
        plt.title("DROP-WAVE FUNCTION - mean values per iteration")
        plt.xlabel('Iterations')
        plt.ylabel('Means')
        plt.savefig("means.png")
        plt.clf()
        plt.cla()

        plt.plot(standardDeviations)
        plt.title("DROP-WAVE FUNCTION - standard deviations per iteration")
        plt.xlabel('Iterations')
        plt.ylabel('Standard deviations')
        plt.savefig("standard_deviations.png")
        plt.clf()
        plt.cla()


    def runGen(self, epNo, poNo):
        print("poczatek testu")
        # l = 40
        epoki=[]
        for x in range(epNo):
            if(x==0):
                epoki.append(Populacja(poNo))
            else:
                epoki.append(epoki[x-1].epoka())
        epoki[0].print()
        epoki[epNo-1].print()
        self.generateFiles(epoki)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selectionMethodCombo.setItemText(0, _translate("Dialog", "Best"))
        self.label.setText(_translate("Dialog", "Selection method:"))
        self.startRange.setPlaceholderText(_translate("Dialog", "Start range"))
        self.endRange.setPlaceholderText(_translate("Dialog", "End Range"))
        self.populationAmount.setPlaceholderText(_translate("Dialog", "Population amount"))
        self.numberOfEpoch.setPlaceholderText(_translate("Dialog", "Epoch number"))
        self.bestAndTourmamentChromosomeAmount.setPlaceholderText(_translate("Dialog", "Best and tourmament chromosome amount"))
        self.eliteStrategyAmount.setPlaceholderText(_translate("Dialog", "Elite strategy amount"))
        self.crossProbability.setPlaceholderText(_translate("Dialog", "Cross probability"))
        self.mutationProbability.setPlaceholderText(_translate("Dialog", "Mutation probability"))
        self.label_2.setText(_translate("Dialog", "Cross method:"))
        self.crossMethodCombo.setItemText(0, _translate("Dialog", "One_point"))
        self.crossMethodCombo.setItemText(1, _translate("Dialog", "Two_point"))
        self.label_3.setText(_translate("Dialog", "Mutation method:"))
        self.mutationMethodCombo.setItemText(0, _translate("Dialog", "One_point"))
        self.mutationMethodCombo.setItemText(1, _translate("Dialog", "Two_point"))
        self.inversionProbability.setPlaceholderText(_translate("Dialog", "Inversion probability"))
        self.numberOfBits.setPlaceholderText(_translate("Dialog", "Number of bits"))
        self.maximizationCheckBox.setText(_translate("Dialog", "Maximization"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())


